Repository BreadGood-22/frontend, pull requests merged in 2022-12, with the labels that each got.

#7 Feature/button
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/assets/icon-image.svg
  src/components/Button/index.jsx
  src/components/Button/style.js
  src/components/Layout/index.jsx
  src/components/Layout/style.js
  src/components/index.js
  src/pages/SignUp/index.jsx
  src/pages/SignUp/style.js
  src/pages/index.js
  src/router/Router.jsx
  src/style/font.css
Labels: design

#9 design: 로그인, 회원가입, 프로필 설정 페이지 내 공통 입력 버튼 디자인
  src/components/ActiveInputs/index.jsx
  src/components/ActiveInputs/style.js
  src/components/index.js
  src/pages/Signup/index.jsx
  src/pages/Signup/style.js
  src/style/font.css
  src/style/globalStyles.jsx
Labels: design

#11 feat: 네비바 디자인 및 라우터 처리 추가
  src/assets/icon-chat-fill.png
  src/assets/icon-chat.png
  src/assets/icon-edit-fill.png
  src/assets/icon-home-fill.png
  src/assets/icon-home.png
  src/assets/icon-post-fill.png
  src/assets/icon-post.png
  src/assets/icon-profile-fill.png
  src/assets/icon-profile.png
  src/components/Navbar/index.jsx
  src/components/Navbar/style.js
  src/components/index.js
  src/pages/Chat/index.jsx
  src/pages/Chat/style.js
  src/pages/Home/index.jsx
  src/pages/Home/style.js
  src/pages/PostUpload/index.jsx
  src/pages/PostUpload/style.js
  src/pages/Profile/index.jsx
  src/pages/Profile/style.js
  src/pages/index.js
  src/router/Router.jsx
Labels: design, feature

#12 design: 공통 컴포넌트 - 헤더 디자인 #6
  src/assets/icons/icon-arrow-left.svg
  src/assets/icons/icon-image.svg
  src/assets/icons/icon-more-vertical.svg
  src/assets/icons/icon-search.svg
  src/components/Button/style.js
  src/components/Header/index.jsx
  src/components/Header/style.js
  src/components/index.js
  src/style/theme.jsx
Labels: design

#19 design: start 페이지 UI 구현 및 라우터 처리 #14
  src/assets/icons/icon-facebook.svg
  src/assets/icons/icon-google.svg
  src/assets/icons/icon-kakao.svg
  src/assets/images/symbol-logo.png
  src/assets/images/symbol-logo.svg
  src/components/Start/SocialButtons/index.jsx
  src/components/Start/SocialButtons/style.js
  src/components/Start/index.jsx
  src/components/Start/style.js
  src/components/index.js
  src/pages/Start/index.jsx
  src/pages/Start/style.js
Labels: design

#20 refactor: start 페이지 마크업 변경
  src/pages/Start/index.jsx
  src/pages/Start/style.js
Labels: refactor

#21 design: 회원가입 페이지 UI 구현 및 라우터 처리
  src/components/Button/index.jsx
  src/components/Button/style.js
  src/pages/Signup/index.jsx
  src/pages/Signup/style.js
Labels: design

#22 design/feat: 로그인 페이지 UI 및 기능 구현
  .gitignore
  package-lock.json
  package.json
  src/api/apiController.js
  src/context/AuthProvider.js
  src/index.js
  src/pages/Login/index.jsx
  src/pages/Login/style.js
Labels: design, feature

#23 design: 프로필 설정 UI 구현
  src/assets/images/basic-profile-img.png
  src/assets/images/upload-file.png
  src/pages/ProfileSetting/index.jsx
  src/pages/ProfileSetting/style.js
Labels: design

#27 feat: 로그인 기능 구현
  .eslintrc.json
  src/components/common/ActiveInputs/style.js
  src/components/common/Button/index.jsx
  src/components/common/Button/style.js
  src/components/login/LoginForm/index.jsx
  src/components/login/LoginForm/style.js
  src/pages/ErrorPage/index.jsx
  src/pages/ErrorPage/style.js
  src/pages/index.js
  src/router/ProtectedRoute.jsx
  src/router/PublicRoute.jsx
  src/router/Router.jsx
Labels: feature

#32 [feat] 회원가입 페이지 기능 구현
  package-lock.json
  package.json
  src/components/signup/SignupForm/index.jsx
Labels: feature

#33 design: 프로필 페이지 UI 구현
  src/assets/icons/icon-chat.svg
  src/assets/icons/icon-heart-off.svg
  src/assets/icons/icon-heart-on.png
  src/assets/icons/icon-heart-on.svg
  src/assets/icons/icon-post-gallery-off.svg
  src/assets/icons/icon-post-gallery-on.svg
  src/assets/icons/icon-post-list-off.svg
  src/assets/icons/icon-post-list-on.svg
  src/assets/icons/icon-share.svg
  src/components/common/Header/index.jsx
  src/components/common/Header/style.js
  src/components/common/Navbar/style.js
  src/components/common/PostList/index.jsx
  src/components/common/PostList/style.js
  src/components/index.js
  src/components/profile/PostGallery/index.jsx
  src/components/profile/PostGallery/style.js
  src/components/profile/PostsContainer/index.jsx
  src/components/profile/PostsContainer/style.js
  src/components/profile/ProductsContainer/index.jsx
  src/components/profile/ProductsContainer/style.js
  src/components/profile/UserInfoContainer/index.jsx
  src/components/profile/UserInfoContainer/style.js
  src/pages/AddProductPage/index.jsx
  src/pages/FollowerPage/index.jsx
  src/pages/FollowingPage/index.jsx
  src/pages/ProfileEditPage/index.jsx
  src/pages/ProfilePage/index.jsx
  src/pages/ProfilePage/style.js
  src/pages/index.js
  src/router/Router.jsx
  src/style/theme.jsx
Labels: design

#34 design: 게시글 작성 페이지 UI 구현
  src/assets/icons/icon-image.svg
  src/assets/icons/icon-img-remove.svg
  src/assets/icons/icon-upload-middle.svg
  src/assets/icons/icon-upload-small-brown.svg
  src/assets/icons/icon-upload-small-lg.svg
  src/components/common/Button/index.jsx
  src/components/common/Button/style.js
  src/components/common/Header/index.jsx
  src/components/index.js
  src/components/postUpload/Photo/index.jsx
  src/components/postUpload/Photo/style.js
  src/components/postUpload/PhotoUploadList/index.jsx
  src/components/postUpload/PhotoUploadList/style.js
  src/components/postUpload/PostUploadForm/index.jsx
  src/components/postUpload/PostUploadForm/style.js
  src/pages/PostUploadPage/index.jsx
  src/pages/PostUploadPage/style.js
Labels: design

#38 feat: 프로필 페이지 관련 기능 구현
  .eslintrc.json
  src/components/common/Header/style.js
  src/components/common/LikeButton/index.jsx
  src/components/common/LikeButton/style.js
  src/components/common/Navbar/index.jsx
  src/components/common/PostList/index.jsx
  src/components/common/PostList/style.js
  src/components/index.js
  src/components/login/LoginForm/index.jsx
  src/components/profile/PostGallery/index.jsx
  src/components/profile/PostGallery/style.js
  src/components/profile/PostsContainer/index.jsx
  src/components/profile/PostsContainer/style.js
  src/components/profile/ProductsContainer/index.jsx
  src/components/profile/ProductsContainer/style.js
  src/components/profile/UserInfoContainer/index.jsx
  src/pages/PostPage/index.jsx
  src/pages/ProfilePage/style.js
  src/pages/index.js
  src/router/Router.jsx
Labels: design, feature

#39 design: 공통 컴포넌트 - 모달창 디자인 구현
  src/components/common/Header/index.jsx
  src/components/common/Modal/index.jsx
  src/components/common/Modal/style.js
  src/components/common/PostList/index.jsx
  src/components/index.js
  src/components/profile/PostsContainer/index.jsx
  src/pages/ProfilePage/index.jsx
Labels: design

#41 [design] 공통 컴포넌트 - 모달창 디자인 구현 (추가)
  src/components/common/Modal/index.jsx
  src/components/index.js
  src/components/profile/ProductsContainer/index.jsx
  src/components/profile/ProductsContainer/style.js
Labels: design

#43 feat: 프로필 페이지 모달 내 기능 구현
  src/components/common/Modal/index.jsx
  src/components/common/PostList/index.jsx
  src/components/profile/PostsContainer/index.jsx
  src/components/profile/ProductsContainer/index.jsx
  src/pages/PostEditPage/index.jsx
  src/pages/ProductEditPage/index.jsx
  src/pages/index.js
  src/router/Router.jsx
Labels: feature

#44 feat: 게시글 작성 페이지 기능 구현
  src/api/apiController.js
  src/components/common/Button/index.jsx
  src/components/common/Header/index.jsx
  src/components/postUpload/Photo/index.jsx
  src/components/postUpload/PhotoUploadList/index.jsx
  src/components/postUpload/PostUploadForm/index.jsx
  src/components/postUpload/PostUploadForm/style.js
  src/pages/PostUploadPage/index.jsx
  src/style/globalStyles.jsx
Labels: feature

#48 fix: 공통 컴포넌트 - 이미지 업로드 버튼 수정
  src/components/common/Button/index.jsx
  src/components/common/Button/style.js
  src/components/index.js
Labels: fix

#49 design: 댓글, 댓글 입력창 컴포넌트 디자인
  src/components/comment/Comment/index.jsx
  src/components/comment/Comment/style.js
  src/components/comment/CommentInput/index.jsx
  src/components/comment/CommentInput/style.js
  src/components/common/Post/index.jsx
  src/components/common/Post/style.js
  src/components/common/PostList/index.jsx
  src/components/common/PostList/style.js
  src/components/index.js
  src/pages/PostPage/index.jsx
  src/pages/PostPage/style.js
Labels: design

#50 design: 상품 등록 페이지 UI 구현
  src/components/addProduct/addProductForm/index.jsx
  src/components/addProduct/addProductForm/style.js
  src/components/common/Header/index.jsx
  src/components/index.js
  src/pages/AddProductPage/index.jsx
Labels: design

#53 fix: 프로필 페이지에 게시글 나타나지 않는 현상 해결
  src/components/comment/CommentInput/style.js
  src/components/common/Post/index.jsx
  src/pages/PostPage/index.jsx
Labels: fix

#57 feat: 게시글 페이지 기능 구현
  src/components/comment/Comment/index.jsx
  src/components/comment/CommentInput/index.jsx
  src/components/comment/CommentList/index.jsx
  src/components/comment/CommentList/style.js
  src/components/common/Layout/style.js
  src/components/common/Modal/index.jsx
  src/components/common/Post/index.jsx
  src/components/index.js
  src/components/post/PostContainer/index.jsx
  src/components/post/PostContainer/style.js
  src/pages/PostPage/index.jsx
  src/utils/timeForToday.js
Labels: feature

#59 design: 팔로워/팔로잉 페이지 UI 구현
  src/components/common/Header/index.jsx
  src/components/follow/Follow/index.jsx
  src/components/follow/Follow/style.js
  src/components/index.js
  src/pages/FollowerPage/index.jsx
  src/pages/FollowerPage/style.js
  src/pages/FollowingPage/index.jsx
  src/pages/FollowingPage/style.js
Labels: design

#63 feat: 상품 등록 페이지 기능 구현
  src/components/addProduct/addProductForm/index.jsx
  src/components/addProduct/addProductForm/style.js
  src/components/common/Button/index.jsx
  src/components/common/Header/index.jsx
Labels: feature

#65 feat: 팔로워/팔로잉 페이지 기능 구현
  src/components/common/Button/index.jsx
  src/components/follow/Follow/index.jsx
  src/components/follow/Follow/style.js
  src/pages/FollowerPage/index.jsx
  src/pages/FollowingPage/index.jsx
Labels: feature

#69 feat: 홈페이지 기능 구현
  src/components/common/Modal/index.jsx
  src/components/profile/PostsContainer/index.jsx
  src/hooks/useIntersect.js
  src/index.js
  src/pages/HomePage/index.jsx
  src/pages/HomePage/style.js
Labels: feature

#71 fix: 공통 컴포넌트 Post 네비바에 가려지는 이슈 해결
  src/components/common/PostList/index.jsx
  src/components/common/PostList/style.js
  src/components/profile/PostGallery/index.jsx
  src/components/profile/PostGallery/style.js
  src/components/profile/PostsContainer/style.js
Labels: fix

#73 design: splash 화면 구현
  src/assets/images/splash.svg
  src/components/index.js
  src/components/start/Splash/index.jsx
  src/components/start/Splash/style.js
  src/pages/StartPage/index.jsx
  src/pages/StartPage/style.js
Labels: design

#75 refactor: 로그인 폼에 react-hook-form 적용
  src/components/login/LoginForm/index.jsx
Labels: refactor

#76 design: 채팅방 페이지 UI 구현
  src/assets/images/chat-example-img.png
  src/components/chatRoom/ChatContents/index.jsx
  src/components/chatRoom/ChatContents/style.js
  src/components/chatRoom/ChatInput/index.jsx
  src/components/chatRoom/ChatInput/style.js
  src/components/common/Header/index.jsx
  src/components/common/Modal/index.jsx
  src/components/index.js
  src/pages/ChatListPage/index.jsx
  src/pages/ChatListPage/style.js
  src/pages/ChatRoomPage/index.jsx
  src/pages/index.js
  src/router/Router.jsx
Labels: design

#80 Feature/refactor 3
  src/assets/images/full-logo.png
  src/assets/images/splash.svg
  src/components/common/ActiveInputs/style.js
  src/components/common/Header/style.js
  src/components/common/PostList/style.js
  src/components/home/NoFollowings/style.js
  src/components/postUpload/PostUploadForm/style.js
  src/components/start/LoginButtons/style.js
  src/components/start/Splash/style.js
  src/pages/HomePage/index.jsx
  src/pages/HomePage/style.js
  src/pages/LoginPage/style.js
  src/pages/SignupPage/style.js
  src/pages/StartPage/style.js
Labels: refactor

#82 feat: 프로필 페이지 프로필 이미지 axios 통신
  src/components/profile/UserInfoContainer/index.jsx
  src/components/profile/UserInfoContainer/style.js
Labels: feature

#84 design: 게시글 등록/수정 페이지 뒤로가기 버튼 모달 구현
  src/components/common/Header/index.jsx
  src/components/common/Modal/index.jsx
  src/components/common/Modal/style.js
  src/components/index.js
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/PostUploadForm/index.jsx
Labels: design

#86 feat: 검색 페이지 구현
  src/components/common/Header/index.jsx
  src/components/index.js
  src/components/search/SearchCard/index.jsx
  src/components/search/SearchCard/style.js
  src/hooks/useDebounce.js
  src/pages/SearchPage/index.jsx
  src/pages/SearchPage/style.js
Labels: feature

#87 fix: 프로필 미설정 시 기본 이미지 변경
  src/components/common/Post/index.jsx
  src/components/follow/Follow/index.jsx
  src/components/profile/UserInfoContainer/index.jsx
Labels: fix

#89 refactor: 포스트 업로드/수정 페이지 이미지 URL 수정 및 이미지 스크롤 현상 해결
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/PhotoUploadList/style.js
  src/components/postUpload/PostUploadForm/index.jsx
Labels: refactor

#91 fix: 포스트 업로드/수정 axios 통신 에러핸들링
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/PostUploadForm/index.jsx
Labels: fix

#95 feat/fix: 프로필 페이지 팔로우/언팔로우 기능 구현 및 에러 핸들링
  src/components/common/Button/index.jsx
  src/components/profile/PostsContainer/index.jsx
  src/components/profile/ProductsContainer/index.jsx
  src/components/profile/UserInfoContainer/index.jsx
  src/components/profile/UserInfoContainer/style.js
Labels: feature, fix

#94 fix: 팔로우 기능 axios 통신 에러핸들링
  src/components/follow/Follow/index.jsx
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/PostUploadForm/index.jsx
  src/pages/FollowerPage/index.jsx
  src/pages/FollowingPage/index.jsx
Labels: fix

#98 fix: 상품 등록/수정 페이지 에러 핸들링
  src/components/addProduct/addProductForm/index.jsx
  src/components/productEdit/ProductEditForm/index.jsx
Labels: fix

#99 feat: 댓글 프로필 이미지 axios 처리 및 프로필 이동 구현
  src/components/comment/Comment/index.jsx
  src/components/comment/CommentInput/index.jsx
  src/components/comment/CommentInput/style.js
Labels: feature

#101 fix: 포스트 업로드/수정 페이지 프로필 미설정 시 기본 이미지 수정
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/PostUploadForm/index.jsx
Labels: fix

#103 design: 팔로우 프로필 네모로 보이는 현상 해결
  src/components/follow/Follow/style.js
Labels: design

#104 fix: 프로필 이미지 렌더링 함수 비교 URL 수정
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/PostUploadForm/index.jsx
Labels: fix

#105 fix: 프로필 페이지 오류 수정 및 기본 프로필 이미지 설정
  src/components/comment/Comment/index.jsx
  src/components/comment/CommentInput/index.jsx
  src/components/common/Modal/index.jsx
  src/components/common/Post/index.jsx
  src/components/profile/PostsContainer/index.jsx
  src/components/profile/ProductsContainer/index.jsx
  src/components/profile/UserInfoContainer/index.jsx
Labels: fix

#108 feat: 포스트 유저 프로필/이름 클릭 시 프로필 페이지로 이동 기능 구현
  src/components/common/Post/index.jsx
Labels: feature

#109 refactor: axios 통신을 try/catch 에러 핸들링으로 리팩토링
  src/components/login/LoginForm/index.jsx
  src/pages/HomePage/index.jsx
  src/pages/PostPage/index.jsx
Labels: refactor

#110 [feat] 프로필 설정 페이지 기능 구현
  src/components/common/Button/style.js
  src/components/profileSetting/ProfileForm/index.jsx
  src/components/profileSetting/ProfileForm/style.js
  src/pages/ProfileSettingPage/index.jsx
Labels: feature

#112 feat: 프로필 설정 페이지 axios 통신 및 세부 수정
  src/components/profileSetting/ProfileForm/index.jsx
  src/components/profileSetting/ProfileForm/style.js
Labels: feature

#114 fix: 회원가입 페이지 에러 핸들링
  src/components/signup/SignupForm/index.jsx
Labels: fix

#115 rename: 상품 등록 페이지 폴더명 파스칼 케이스로 변경
  src/components/addProduct/AddProductForm/index.jsx
  src/components/addProduct/AddProductForm/style.js
  src/components/index.js
Labels: rename

#117 fix: 전체 페이지 오류 수정
  src/components/comment/Comment/style.js
  src/components/comment/CommentInput/style.js
  src/components/common/Button/style.js
  src/components/common/Post/index.jsx
  src/components/common/Post/style.js
  src/components/follow/Follow/style.js
  src/components/postEdit/PostEditForm/style.js
  src/components/postUpload/PostUploadForm/style.js
  src/components/profile/UserInfoContainer/style.js
  src/components/profileSetting/ProfileForm/index.jsx
  src/components/profileSetting/ProfileForm/style.js
  src/components/search/SearchCard/style.js
  src/router/ProtectedRoute.jsx
Labels: fix

#119 feat: og 태그 추가 #118
  public/favicon.ico
  public/index.html
  public/og-image.png
Labels: chore
