Repository BreadGood-22/frontend, pull requests merged in 2023-01, with the labels that each got.

#123 design: 공통 컴포넌트 - 모달 버튼 너비 설정
  src/components/common/Modal/style.js
Labels: design

#126 fix: 게시글이 적어도 스크롤되는 현상 해결
  src/components/comment/Comment/style.js
  src/components/comment/CommentList/index.jsx
  src/components/comment/CommentList/style.js
  src/components/common/Post/style.js
  src/components/common/PostList/index.jsx
  src/components/common/PostList/style.js
  src/components/profile/PostGallery/index.jsx
  src/components/profile/PostsContainer/index.jsx
  src/hooks/useHeight.js
  src/hooks/useIntersect.js
  src/pages/HomePage/index.jsx
  src/pages/PostPage/index.jsx
Labels: fix

#128 fix: limit, skip을 사용해 댓글 리스트 API 요청 #127
  src/components/comment/CommentInput/index.jsx
  src/components/comment/CommentList/index.jsx
  src/components/common/Modal/index.jsx
  src/pages/PostPage/index.jsx
Labels: fix

#130 fix: 다른 유저의 프로필 페이지에서 게시글 더보기 클릭시 신고하기 모달 나타나도록 수정 #129
  src/components/profile/PostsContainer/index.jsx
Labels: fix

#132 fix: 팔로우 덜 불러와지는 현상 해결
  src/pages/FollowerPage/index.jsx
  src/pages/FollowerPage/style.js
  src/pages/FollowingPage/index.jsx
  src/pages/FollowingPage/style.js
Labels: fix

#131 design: 프로필 페이지 마크업 수정
  src/pages/ProfilePage/style.js
Labels: design

#135 refactor: follow 기본 이미지 basic Profile URL env에서 불러오도록 수정
  src/components/follow/Follow/index.jsx
Labels: refactor

#137 refactor 로그인 폼 에러 메시지 react-hook-form 라이브러리로 처리
  src/components/common/ActiveInputs/index.jsx
  src/components/login/LoginForm/index.jsx
Labels: refactor

#139 fix: 홈페이지 피드 로딩중 수정
  src/pages/HomePage/index.jsx
Labels: fix

#141 refactor: start 페이지 로고 alt값 추가
  src/pages/StartPage/index.jsx
Labels: refactor, perf

#144 fix: 프로필 페이지 등록된 상품 이름이 긴 경우 말줄임 처리
  src/components/profile/ProductsContainer/style.js
Labels: fix

#146 fix: 로그인 페이지 경고 문구 나타날 때 로그인 버튼 밀리는 현상 수정
  src/components/login/LoginForm/index.jsx
  src/components/login/LoginForm/style.js
Labels: fix

#147 refactor: 상품 등록/수정 페이지 Form 컴포넌트 통합
  src/components/addProduct/AddProductForm/index.jsx
  src/components/index.js
  src/components/product/ProductForm/index.jsx
  src/components/product/ProductForm/style.js
  src/components/productEdit/ProductEditForm/style.js
  src/pages/AddProductPage/index.jsx
  src/pages/ProductEditPage/index.jsx
Labels: refactor

#148 feat: 포스트 이미지 최대 3장까지 업로드 기능 구현
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/Photo/index.jsx
  src/components/postUpload/Photo/style.js
  src/components/postUpload/PhotoUploadList/index.jsx
  src/components/postUpload/PhotoUploadList/style.js
  src/components/postUpload/PostUploadForm/index.jsx
Labels: feature

#150 refactor: api 로직 분리
  src/api/comment/getComments.js
  src/api/imgUpload/addImage.js
  src/api/index.js
  src/api/post/getPosts.js
  src/api/profile/getUserInfo.js
Labels: refactor

#154 refactor: 회원가입 및 프로필 설정 페이지 API 로직 분리
  src/api/index.js
  src/api/profile/getUserInfo.js
  src/api/signup/addAccountNameValid.js
  src/api/signup/addEmailValid.js
  src/api/signup/addUserInfo.js
  src/components/profileSetting/ProfileForm/index.jsx
  src/components/profileSetting/ProfileForm/style.js
  src/components/signup/SignupForm/index.jsx
  src/components/signup/SignupForm/style.js
Labels: refactor

#157 refactor: 포스트/팔로우 기능 API 로직 분리
  src/api/follow/addFollow.js
  src/api/follow/deleteFollow.js
  src/api/follow/getFollowers.js
  src/api/follow/getFollowings.js
  src/api/index.js
  src/api/post/addPost.js
  src/api/post/getUserPost.js
  src/api/post/updatePost.js
  src/api/profile/getUserInfo.js
  src/components/follow/Follow/index.jsx
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/PostUploadForm/index.jsx
  src/pages/FollowerPage/index.jsx
  src/pages/FollowingPage/index.jsx
Labels: refactor

#156 refactor: 상품 등록/수정 페이지 API 로직 분리
  src/api/index.js
  src/api/product/addProduct.js
  src/api/product/getProductDetail.js
  src/api/product/updateProduct.js
  src/components/product/ProductForm/index.jsx
Labels: refactor

#158 fix: 회원가입 및 프로필 설정 페이지 API 로직 구조분해할당으로 통일 및 불필요한 객체 제거
  src/api/signup/addUserInfo.js
  src/components/profileSetting/ProfileForm/index.jsx
  src/components/signup/SignupForm/index.jsx
Labels: fix

#162 design: 로고 이미지 최적화
  src/assets/images/symbol-logo.webp
  src/pages/StartPage/index.jsx
Labels: design

#163 [fix] 포스트 수정 페이지 textarea 오류 및 빈 이미지 불러오는 현상 해결
  src/api/post/addPost.js
  src/api/post/updatePost.js
  src/components/postEdit/PostEditForm/index.jsx
  src/components/postUpload/PostUploadForm/index.jsx
Labels: fix

#170 refactor: 이미지 업로드 압축 및 상품 등록/수정 페이지 세부 수정
  package-lock.json
  package.json
  src/api/imgUpload/addImage.js
  src/api/imgUpload/imageResize.js
  src/api/product/addProduct.js
  src/api/product/updateProduct.js
  src/components/product/ProductForm/style.js
Labels: refactor, perf, fix

#174 feat: 프로필 수정 페이지 구현 및 프로필 설정/수정 페이지 Form 컴포넌트 통합
  src/api/index.js
  src/api/profile/updateUserInfo.js
  src/components/profileSetting/ProfileForm/index.jsx
  src/components/profileSetting/ProfileForm/style.js
  src/pages/ProfileEditPage/index.jsx
  src/pages/ProfileSettingPage/index.jsx
  src/pages/ProfileSettingPage/style.js
Labels: feature

#176 design: 채팅리스트 UI 구현
  src/components/chat/ChatContents/index.jsx
  src/components/chat/ChatContents/style.js
  src/components/chat/ChatInput/index.jsx
  src/components/chat/ChatInput/style.js
  src/components/chat/ChatList/index.jsx
  src/components/chat/ChatList/style.js
  src/components/chat/chatData.js
  src/components/index.js
  src/pages/ChatListPage/index.jsx
Labels: design

#177 fix: 홈페이지 무한 스크롤 시 맨위로 올라가는 현상 해결
  src/components/common/Loading/index.jsx
  src/components/common/Loading/style.js
  src/components/index.js
  src/components/post/Post/index.jsx
  src/components/post/PostList/index.jsx
  src/pages/HomePage/index.jsx
Labels: fix

#179 feat: 404 페이지 구현
  src/assets/images/404.webp
  src/components/common/NotFound/index.jsx
  src/components/common/NotFound/style.js
  src/components/index.js
  src/pages/ErrorPage/index.jsx
  src/pages/ErrorPage/style.js
  src/pages/NotFoundPage/index.jsx
  src/pages/index.js
  src/router/Router.jsx
Labels: design, feature
